export const data = [
  {
      "group_name": "Pantry Essentials",
      "icon": "All cuisines.png",
      "ingredients": [
          "butter",
          "egg",
          "garlic",
          "milk",
          "onion",
          "sugar",
          "flour",
          "olive oil",
          "garlic powder",
          "white rice",
          "cinnamon",
          "ketchup",
          "soy sauce",
          "mayonnaise",
          "vegetable oil",
          "bread",
          "baking powder",
          "brown sugar",
          "oregano",
          "potato",
          "honey",
          "paprika",
          "baking soda",
          "vanilla",
          "spaghetti",
          "peanut butter",
          "chili powder",
          "cumin",
          "mustard",
          "chicken breast",
          "cheddar",
          "onion powder",
          "carrot",
          "tomato",
          "basil",
          "parsley",
          "parmesan",
          "italian seasoning",
          "thyme",
          "bell pepper"
      ]
  },
  {
      "group_name": "Vegetables & Greens",
      "icon": "vegetables.png",
      "ingredients": [
          "garlic",
          "onion",
          "bell pepper",
          "carrot",
          "scallion",
          "tomato",
          "potato",
          "red onion",
          "celery",
          "jalapeno",
          "avocado",
          "zucchini",
          "shallot",
          "cherry tomato",
          "cucumber",
          "spinach",
          "corn",
          "chile pepper",
          "sweet potato",
          "broccoli",
          "baby greens",
          "pumpkin",
          "cabbage",
          "cauliflower",
          "asparagus",
          "arugula",
          "leek",
          "kale",
          "eggplant",
          "lettuce",
          "butternut squash",
          "romaine",
          "beetroot",
          "brussels sprout",
          "fennel",
          "sun dried tomato",
          "radish",
          "red cabbage",
          "artichoke",
          "new potato",
          "summer squash",
          "mixed greens",
          "parsnip",
          "baby carrot",
          "mixed vegetable",
          "poblano pepper",
          "sweet pepper",
          "green tomato",
          "serrano pepper",
          "watercress",
          "iceberg",
          "mashed potatoes",
          "horseradish",
          "chard",
          "hash browns",
          "napa cabbage",
          "pimiento",
          "butter lettuce",
          "spaghetti squash",
          "celeriac",
          "turnip",
          "bok choy",
          "okra",
          "acorn squash",
          "corn cob",
          "radicchio",
          "water chestnut",
          "pearl onion",
          "pepperoncini",
          "tenderstem broccoli",
          "leaf lettuce",
          "cavolo nero",
          "baby bok choy",
          "endive",
          "plantain",
          "collard greens",
          "jicama",
          "habanero pepper",
          "corn husk",
          "french-fried onions",
          "daikon",
          "baby corn",
          "broccoli rabe",
          "belgian endive",
          "rutabaga",
          "kohlrabi",
          "boston lettuce",
          "fresno chile",
          "yam",
          "microgreens",
          "ancho chile peppers",
          "delicata squash",
          "anaheim pepper",
          "cress",
          "frisee",
          "broccoli slaw",
          "potato flakes",
          "golden beet",
          "gem lettuce",
          "banana pepper"
      ]
  },
  {
      "group_name": "Mushrooms",
      "icon": "mushrooms.png",
      "ingredients": [
          "button mushroom",
          "shiitake mushroom",
          "portobello mushroom",
          "wild mushroom",
          "porcini",
          "oyster mushroom",
          "mixed mushrooms",
          "chestnut mushroom",
          "enoki mushroom",
          "black fungus",
          "black truffle",
          "morel mushrooms",
          "field mushroom",
          "king oyster mushroom",
          "straw mushroom",
          "shimeji mushroom",
          "dried chinese mushroom",
          "maitake",
          "trumpet mushroom",
          "white truffle",
          "white fungus",
          "pioppini",
          "snow fungus",
          "white beech mushroom",
          "huitlacoche",
          "matsutake",
          "nameko",
          "boletus",
          "djon djon mushroom",
          "mixed asian mushrooms",
          "puffball",
          "honey fungus",
          "lobster mushroom",
          "saffron milk caps",
          "caesar's mushroom",
          "candy cap mushrooms",
          "lion’s mane mushroom"
      ]
  },
  {
      "group_name": "Fruits",
      "icon": "fruits.png",
      "ingredients": [
          "lemon",
          "lime",
          "apple",
          "banana",
          "orange",
          "raisins",
          "pineapple",
          "mango",
          "peach",
          "date",
          "coconut",
          "craisins",
          "pear",
          "pomegranate",
          "grape",
          "watermelon",
          "rhubarb",
          "dried apricot",
          "kiwi",
          "grapefruit",
          "plum",
          "fig",
          "apricot",
          "mandarin",
          "currant",
          "prunes",
          "sultanas",
          "cantaloupe",
          "passion fruit",
          "papaya",
          "nectarine",
          "tamarind",
          "dried fig",
          "chestnut",
          "meyer lemon",
          "dried fruit",
          "honeydew melon",
          "clementine",
          "persimmon",
          "melon",
          "tangerine",
          "dried mango",
          "dried apple",
          "quince",
          "banana chips",
          "kumquat",
          "guava",
          "jackfruit",
          "mixed fruit",
          "asian pear",
          "dragon fruit",
          "dried pineapple",
          "lychee",
          "young coconut",
          "kaffir lime",
          "star fruit",
          "green mango",
          "green papaya",
          "dried pears",
          "pomelo",
          "chestnut puree",
          "calamansi",
          "prickly pear",
          "apple chips",
          "yuzu",
          "dried peach",
          "granadilla",
          "mixed peel",
          "kokum",
          "dried lime",
          "tangelo",
          "jujube",
          "young jackfruit",
          "sweet lime",
          "custard-apple",
          "dried lemon",
          "durian",
          "honey date",
          "freeze-dried apple",
          "wood apple",
          "dried tamarind",
          "ice-apple",
          "tamarillo",
          "longan",
          "physalis",
          "finger lime",
          "bitter orange",
          "feijoa",
          "chikoo",
          "dried persimmons",
          "dried orange slice",
          "fig leaves",
          "rambutan",
          "crabapple",
          "rose apple",
          "loquat",
          "pluot",
          "freeze-dried pineapple",
          "soursop",
          "bergamot orange"
      ]
  },
  {
      "group_name": "Berries",
      "icon": "berries.png",
      "ingredients": [
          "strawberry",
          "blueberry",
          "raspberry",
          "cranberry",
          "cherry",
          "blackberry",
          "berry mix",
          "dried cherry",
          "sour cherry",
          "dried blueberries",
          "goji berry",
          "freeze-dried strawberry",
          "gooseberry",
          "freeze-dried raspberry",
          "lingonberry",
          "acai berry",
          "mulberry",
          "amla",
          "elderberry",
          "freeze-dried blueberry",
          "huckleberry",
          "dried elderberry",
          "barberry",
          "black raspberry",
          "dried berries",
          "boysenberry",
          "saskatoon berry",
          "rosehip",
          "sea buckthorn",
          "hawthorn",
          "cloudberry",
          "freeze-dried berries",
          "chokeberry",
          "aronia berry",
          "loganberry",
          "acerola",
          "blackcurrant leaves",
          "haskap berry",
          "sloe berry",
          "oregon grape"
      ]
  },
  {
      "group_name": "Nuts & Seeds",
      "icon": "seeds.png",
      "ingredients": [
          "walnut",
          "pecan",
          "almond",
          "sesame seed",
          "cashew",
          "pine nut",
          "pistachio",
          "peanut",
          "chia",
          "slivered almonds",
          "pumpkin seeds",
          "hazelnut",
          "poppy seed",
          "sunflower seeds",
          "flax",
          "chopped nuts",
          "macadamia",
          "roasted peanuts",
          "hemp hearts",
          "nigella seeds",
          "mixed nuts",
          "brazil nut",
          "mixed seeds",
          "smoked almond",
          "onion seed",
          "watermelon seeds",
          "honey-roasted peanuts",
          "melon seeds",
          "black walnut",
          "lotus seeds",
          "white chia",
          "trail mix",
          "basil seeds",
          "candlenut",
          "peanut brittle",
          "jackfruit seeds",
          "chironji",
          "honey-roasted almond",
          "honey-roasted pecans",
          "toasted nuts",
          "tigernuts",
          "sriracha almond",
          "sunflower sprouts",
          "chia powder",
          "apricot kernels",
          "honey-roasted cashew",
          "milk thistle seeds",
          "ginkgo nuts",
          "palm seeds",
          "keto trail mix",
          "wattleseeds",
          "barùkas",
          "indian almond"
      ]
  },
  {
      "group_name": "Cheeses",
      "icon": "cheese.png",
      "ingredients": [
          "parmesan",
          "cream cheese",
          "cheddar",
          "mozzarella",
          "feta",
          "ricotta",
          "sharp cheddar",
          "monterey jack",
          "blue cheese",
          "goat cheese",
          "fresh mozzarella",
          "swiss cheese",
          "pecorino",
          "gruyere",
          "mascarpone",
          "cottage cheese",
          "american cheese",
          "provolone",
          "mexican cheese blend",
          "pepper jack",
          "brie",
          "paneer",
          "fontina",
          "queso fresco",
          "quark",
          "gouda",
          "cotija",
          "asiago",
          "smoked cheese",
          "halloumi",
          "chevre",
          "italian cheese blend",
          "neufchatel",
          "manchego",
          "herb cream cheese",
          "havarti",
          "colby",
          "burrata",
          "grana-padano",
          "muenster",
          "string cheese",
          "camembert",
          "soft cheese",
          "stilton",
          "raclette",
          "cheddar-jack cheese",
          "colby-jack cheese",
          "taleggio",
          "jarlsberg cheese",
          "creamy cheese wedge",
          "labneh",
          "edam",
          "oaxaca",
          "baby swiss cheese",
          "fromage blanc",
          "marble cheese",
          "kefalotyri",
          "leicester",
          "mizithra",
          "seasoned feta cheese",
          "asadero",
          "lancashire",
          "kasseri",
          "sheep cheese",
          "babybel",
          "scamorza",
          "longhorn",
          "comté",
          "graviera",
          "wensleydale",
          "cambozola",
          "cheshire cheese",
          "chenna",
          "anthotyro",
          "garlic-and-herb goat cheese",
          "hard goat cheese",
          "kashkaval",
          "amul cheese",
          "reblochon",
          "robiola",
          "manouri",
          "queso quesadilla",
          "quick-melt cheese",
          "brick cheese",
          "farmer's cheese",
          "mimolette",
          "panela cheese",
          "stracchino cheese",
          "bergkäse",
          "caciocavallo",
          "vacherin",
          "brown cheese",
          "fontal",
          "gloucester",
          "derby cheese",
          "flemish cheese",
          "truffle cheese",
          "epoisses cheese",
          "limburger",
          "petit-suisse"
      ]
  },
  {
      "group_name": "Dairy & Eggs",
      "icon": "dairy_no_cheese.png",
      "ingredients": [
          "butter",
          "egg",
          "milk",
          "heavy cream",
          "sour cream",
          "buttermilk",
          "yogurt",
          "greek yogurt",
          "cream",
          "whipped cream",
          "ghee",
          "shortening",
          "half and half",
          "sweetened condensed milk",
          "condensed milk",
          "ice cream",
          "margarine",
          "creme fraiche",
          "frosting",
          "milk powder",
          "curd",
          "thickened cream",
          "lemon curd",
          "custard",
          "dulce de leche",
          "chocolate frosting",
          "kefir",
          "liquid egg substitute",
          "sherbet",
          "chocolate milk",
          "hung curd",
          "whey",
          "quail egg",
          "buttermilk powder",
          "frozen yogurt",
          "khoya",
          "coffee creamer",
          "clotted cream",
          "cheese curd",
          "milk cream",
          "goat milk",
          "sour milk",
          "ganache",
          "duck egg",
          "salted egg",
          "skyr",
          "pumpkin spice coffee creamer",
          "yogurt starter",
          "honey greek yogurt",
          "lime curd",
          "raw milk",
          "powdered coffee creamer",
          "milkfat",
          "rainbow sherbet",
          "strawberry frosting",
          "amul butter",
          "goat yogurt",
          "honey butter",
          "cajeta",
          "strawberry cream cheese",
          "goat butter",
          "cookies n' cream ice cream",
          "passionfruit curd",
          "century egg",
          "orange curd",
          "starter culture",
          "dahi",
          "cinnamon sugar butter spread",
          "bulgarian yogurt",
          "peppermint mocha creamer",
          "tvorog",
          "chantilly",
          "liquid rennet",
          "chocolate milk powder",
          "sheep’s milk yoghurt",
          "strawberry milk",
          "ayran",
          "buffalo milk",
          "yogurt drink",
          "cuajada",
          "evaporated goat milk",
          "sheep milk",
          "vanilla milk",
          "pickled egg",
          "yoplait whips",
          "goat kefir",
          "kashk",
          "lebneh",
          "niter kibbeh",
          "ostrich egg"
      ]
  },
  {
      "group_name": "Dairy-Free & Meat Substitutes",
      "icon": "lactose_free.png",
      "ingredients": [
          "coconut milk",
          "almond milk",
          "almond butter",
          "tofu",
          "coconut cream",
          "vegan butter",
          "non-dairy milk",
          "soy milk",
          "extra firm tofu",
          "silken tofu",
          "coconut butter",
          "kala namak salt",
          "egg replacer",
          "vegan mayonnaise",
          "cashew butter",
          "tempeh",
          "vegan cream cheese",
          "coconut yogurt",
          "vegan parmesan",
          "non-dairy yogurt",
          "seed butter",
          "vegan cheese",
          "nut butter",
          "cashew milk",
          "oat milk",
          "rice milk",
          "vegan sour cream",
          "textured vegetable protein",
          "vegan worcestershire",
          "non-dairy creamer",
          "vegan mozzarella",
          "soy yogurt",
          "coconut whipped cream",
          "vegan sausage",
          "smoked tofu",
          "seitan",
          "coconut milk powder",
          "nut milk",
          "soy cream",
          "non-dairy whipped topping",
          "non-dairy cream",
          "vegan ground beef",
          "condensed coconut milk",
          "vegan burger patty",
          "chocolate almond milk",
          "vegan bacon",
          "vegan pesto",
          "vegan feta",
          "soy curls",
          "soy chorizo",
          "hazelnut butter",
          "vegan ranch",
          "vegetarian oyster sauce",
          "hemp milk",
          "vegan beef",
          "marinated tofu",
          "vegan chicken",
          "dairy-free ice-cream",
          "vegetable suet",
          "coconut paste",
          "almond-coconut milk",
          "vegan fish sauce",
          "vegetarian hot dog",
          "hazelnut milk",
          "vegan caesar dressing",
          "almond pulp",
          "vegan meatballs",
          "maple almond butter",
          "soy milk powder",
          "almond creamer",
          "almond-milk yogurt",
          "vegan cream cheese frosting",
          "coconut bacon",
          "vegan gravy",
          "cashew cheese sauce",
          "falafel mix",
          "soy-free butter",
          "vegan nutella",
          "cashewgurt",
          "coconut fat",
          "hazelnut creamer",
          "tofurky",
          "vegan tzatziki",
          "cashew cream cheese",
          "coconut cream powder",
          "flax milk",
          "macadamia butter",
          "quorn",
          "cricket flour",
          "okara",
          "egg tofu",
          "vegan ham",
          "cashew sour cream",
          "macadamia milk",
          "vegan taco meat",
          "walnut taco meat",
          "ready-made falafel",
          "vegan yogurt starter",
          "banana milk",
          "cinnamon leaf"
      ]
  },
  {
      "group_name": "Meats",
      "icon": "meats.png",
      "ingredients": [
          "bacon",
          "ground beef",
          "beef steak",
          "deli ham",
          "pork chops",
          "sweet italian sausage",
          "pork fillet",
          "prosciutto",
          "beef roast",
          "ground pork",
          "sausage",
          "beef stew meat",
          "pepperoni",
          "chorizo",
          "pancetta",
          "pork shoulder",
          "pork loin",
          "ground lamb",
          "smoked sausage",
          "pork ribs",
          "breakfast sausage",
          "hot dog",
          "beef sirloin",
          "salami",
          "brisket",
          "leg of lamb",
          "kielbasa",
          "beef short ribs",
          "pork belly",
          "hot italian sausage",
          "andouille",
          "boneless lamb",
          "pork roast",
          "ground pork sausage",
          "ground sausage",
          "roast beef",
          "bacon bits",
          "bone-in ham",
          "pork spare ribs",
          "lamb chops",
          "lamb shoulder",
          "beef ribs",
          "veal steak",
          "pork butt",
          "canadian bacon",
          "beef sausage",
          "lamb shank",
          "mutton",
          "venison",
          "ham steak",
          "pulled pork",
          "bratwurst",
          "frozen meatballs",
          "ham hock",
          "mixed ground meat",
          "pork cutlets",
          "rabbit",
          "veal cutlet",
          "soup bones",
          "lamb loin",
          "country style ribs",
          "pork back ribs",
          "mexican chorizo",
          "smoked ham hock",
          "black forest ham",
          "raw chorizo",
          "oxtail",
          "rack of lamb",
          "beef liver",
          "serrano ham",
          "pastrami",
          "hard salami",
          "cocktail sausage",
          "back bacon",
          "salt pork",
          "boneless ham",
          "veal shank",
          "ground venison",
          "lap cheong",
          "blood sausage",
          "fresh sausage",
          "dried beef",
          "mortadella",
          "beef shank",
          "gammon joint",
          "country ham",
          "boneless beef short ribs",
          "ground bison",
          "bologna",
          "burger patty",
          "smoked pork chop",
          "lamb neck",
          "sausage patty",
          "veal roast",
          "beef suet",
          "pork neck",
          "pork stew meat",
          "beef shoulder",
          "steak tips",
          "veal chops"
      ]
  },
  {
      "group_name": "Poultry",
      "icon": "game_and_fowl.png",
      "ingredients": [
          "chicken breast",
          "cooked chicken",
          "chicken thighs",
          "boneless skinless chicken thighs",
          "ground turkey",
          "whole chicken",
          "whole turkey",
          "chicken wings",
          "chicken leg",
          "turkey breast",
          "ground chicken",
          "rotisserie chicken",
          "chicken tenders",
          "turkey sausage",
          "chicken sausage",
          "turkey bacon",
          "duck",
          "duck breast",
          "deli turkey",
          "cornish hen",
          "chicken livers",
          "smoked turkey",
          "turkey meat",
          "chicken quarters",
          "ground turkey sausage",
          "quail",
          "smoked turkey sausage",
          "smoked chicken",
          "turkey thigh",
          "turkey leg",
          "goose",
          "pheasant",
          "turkey pepperoni",
          "chicken bones",
          "chicken nuggets",
          "foie gras",
          "turkey meatballs",
          "chicken giblets",
          "turkey wing",
          "turkey giblets",
          "turkey neck",
          "turkey burger",
          "chicken andouille",
          "chicken gizzards",
          "smoked turkey leg",
          "popcorn chicken",
          "chicken italian sausage",
          "ostrich",
          "turkey kielbasa",
          "chicken feet",
          "chicken-apple sausage",
          "deli chicken",
          "pulled chicken",
          "smoked duck breast",
          "wild game bird",
          "chicken necks",
          "duck confit",
          "pigeon",
          "turkey liver",
          "roast duck",
          "chicken meatballs",
          "chicken teriyaki",
          "guinea fowl",
          "smoked turkey wings",
          "duck liver",
          "chicken curry-cut",
          "chicken schnitzel",
          "chicken roast",
          "grouse",
          "turkey bones",
          "turkey lunch meat",
          "goose liver",
          "turkey roast",
          "capon",
          "young chicken",
          "cooked duck",
          "smoked turkey bacon",
          "chicken bacon",
          "parmesan-crusted chicken",
          "turkey hot dog",
          "turkey rissoles",
          "chicken ham",
          "chicken chorizo",
          "turkey taco meat",
          "chicken frames",
          "duck neck",
          "pulled turkey",
          "chicken gyros",
          "chicken kebab",
          "chicken patty",
          "chicken ribs",
          "duck bacon",
          "turkey tail"
      ]
  },
  {
      "group_name": "Fish",
      "icon": "fish.png",
      "ingredients": [
          "salmon",
          "smoked salmon",
          "cod",
          "tilapia",
          "tuna steak",
          "whitefish",
          "halibut",
          "red snapper",
          "sea bass",
          "trout",
          "fish fillets",
          "catfish",
          "surimi",
          "swordfish",
          "sardines",
          "mahi mahi",
          "sole",
          "mackerel",
          "smoked trout",
          "haddock",
          "caviar",
          "monkfish",
          "smoked haddock",
          "flounder",
          "hot-smoked salmon",
          "perch",
          "hake",
          "salt cod",
          "pollock",
          "smoked mackerel",
          "sea bream",
          "rainbow trout",
          "cuttlefish",
          "grouper",
          "salmon roe",
          "herring",
          "carp",
          "steelhead trout",
          "roe",
          "barramundi",
          "black cod",
          "orange roughy",
          "kingfish",
          "turbot",
          "dried anchovy",
          "rockfish",
          "bangus",
          "branzino",
          "pomfret",
          "battered fish",
          "arctic char",
          "coho salmon",
          "lemon sole",
          "eel",
          "fresh anchovy",
          "pike",
          "swai fish",
          "walleye",
          "yellowtail",
          "john dory",
          "fresh mackerel",
          "salmon trout",
          "smoked eel",
          "basa fish",
          "sturgeon",
          "bluefish",
          "fish balls",
          "red mullet",
          "gurnard",
          "plaice",
          "smoked fish",
          "flathead",
          "pompano",
          "rohu fish",
          "salted salmon",
          "salt fish",
          "whiting",
          "dried fish",
          "fish cake",
          "fish heads",
          "smoked herring",
          "nile perch",
          "salmon burger meat",
          "shark meat",
          "smoked tuna",
          "garoupa",
          "gilt-head bream",
          "zander",
          "alaskan pollock",
          "amberjack",
          "pangasius",
          "salt herring",
          "soused herring",
          "bottarga",
          "korean fish cake",
          "mullet",
          "fish pie mix",
          "galunggong",
          "skipjack tuna",
          "tinapa"
      ]
  },
  {
      "group_name": "Seafood & Seaweed",
      "icon": "seafood.png",
      "ingredients": [
          "shrimp",
          "prawns",
          "crab",
          "scallop",
          "mussel",
          "clam",
          "squid",
          "nori",
          "lobster",
          "oyster",
          "lobster tail",
          "crawfish",
          "octopus",
          "dried shrimp",
          "kombu",
          "bay scallop",
          "wakame",
          "soft-shell crab",
          "scampi",
          "baby squid",
          "mixed seafood",
          "king crab",
          "dried scallops",
          "squid ink",
          "dulse seaweed",
          "bay shrimp",
          "roasted seaweed",
          "kelp",
          "smoked oyster",
          "yaki-nori",
          "kizami nori",
          "hijiki",
          "conch",
          "salted shrimp",
          "mud crab",
          "arame",
          "calamari steak",
          "sea urchin",
          "seaweed salad",
          "abalone",
          "dulse",
          "dried squid",
          "smoked mussel",
          "korean seaweed",
          "prepared crab cake",
          "sea lettuce",
          "sea snails",
          "aonori",
          "jellyfish",
          "ogo seaweed",
          "seaweed caviar",
          "shredded squid",
          "sea moss",
          "langoustine"
      ]
  },
  {
      "group_name": "Herbs & Spices",
      "icon": "spices.png",
      "ingredients": [
          "cinnamon",
          "parsley",
          "cilantro",
          "cumin",
          "basil",
          "thyme",
          "ginger root",
          "garlic powder",
          "oregano",
          "nutmeg",
          "chili flake",
          "chili powder",
          "paprika",
          "cayenne",
          "rosemary",
          "bay leaf",
          "turmeric",
          "clove",
          "onion powder",
          "ginger powder",
          "dill",
          "chive",
          "mint",
          "green cardamom",
          "smoked paprika",
          "fresh mint",
          "coriander powder",
          "sage",
          "coriander",
          "allspice",
          "cracked pepper",
          "peppercorn",
          "mustard powder",
          "white pepper",
          "mustard seed",
          "curry leaves",
          "fennel seed",
          "tarragon",
          "saffron",
          "asafoetida",
          "star anise",
          "marjoram",
          "lemongrass",
          "caraway",
          "garlic granules",
          "celery seed",
          "chipotle powder",
          "chipotle",
          "fenugreek",
          "onion flake",
          "thai chile pepper",
          "ancho chile powder",
          "sumac",
          "dried parsley flakes",
          "fenugreek seed",
          "kashmiri red chilli",
          "thai basil",
          "edible flowers",
          "kaffir lime leaves",
          "aniseed",
          "chervil",
          "lavender",
          "carom seeds",
          "mango powder",
          "mace",
          "dried chives",
          "mexican oregano",
          "black mustard seed",
          "black cardamom",
          "dried chilies",
          "saffron strands",
          "pink peppercorn",
          "hot paprika",
          "lemon thyme",
          "guajillo pepper",
          "galangal",
          "dried cilantro",
          "lemon balm",
          "garlic flakes",
          "dill seed",
          "green peppercorn",
          "aleppo pepper",
          "wasabi powder",
          "gochugaru",
          "savory herb",
          "achiote seeds",
          "pandan leaves",
          "clove powder",
          "sorrel",
          "greek oregano",
          "saigon cinnamon",
          "lemongrass paste",
          "shiso",
          "celery powder",
          "anardana",
          "dried orange peel",
          "black cumin",
          "vietnamese mint",
          "espelette pepper",
          "lemon verbena"
      ]
  },
  {
      "group_name": "Sugar & Sweeteners",
      "icon": "sugar_and_sweeteners.png",
      "ingredients": [
          "sugar",
          "brown sugar",
          "confectioners’ sugar",
          "honey",
          "maple syrup",
          "corn syrup",
          "coconut sugar",
          "molasses",
          "stevia",
          "agave nectar",
          "demerara sugar",
          "sugar syrup",
          "erythritol",
          "vanilla sugar",
          "caramel syrup",
          "chocolate syrup",
          "jaggery",
          "golden syrup",
          "cinnamon sugar",
          "liquid stevia",
          "grenadine",
          "coarse sugar",
          "salted caramel syrup",
          "sanding sugar",
          "dark corn syrup",
          "monk fruit sweetener",
          "sucralose",
          "colored sugar",
          "blackstrap molasses",
          "maple sugar",
          "confectioners' sweetener",
          "glucose",
          "xylitol",
          "brown sugar substitute",
          "jam sugar",
          "brown rice syrup",
          "rock sugar",
          "vanilla syrup",
          "strawberry syrup",
          "coconut syrup",
          "ginger syrup",
          "orgeat",
          "raspberry syrup",
          "pancake syrup",
          "date syrup",
          "rice malt syrup",
          "black treacle",
          "date paste",
          "mint syrup",
          "cinnamon syrup",
          "passion fruit syrup",
          "treacle",
          "rice syrup",
          "maple butter",
          "manuka honey",
          "blueberry syrup",
          "apple syrup",
          "allulose",
          "blackberry syrup",
          "hibiscus syrup",
          "cherry syrup",
          "fresh sugar cane",
          "lavender syrup",
          "pineapple syrup",
          "hazelnut syrup",
          "sorghum syrup",
          "white chocolate sauce",
          "pumpkin spice syrup",
          "glycerine",
          "jaggery syrup",
          "piloncillo",
          "golden sugar",
          "cranberry syrup",
          "lucuma powder",
          "black sugar",
          "cane syrup",
          "mango syrup",
          "malt syrup",
          "hot honey",
          "gula melaka",
          "elderberry syrup",
          "rosemary syrup",
          "dark chocolate syrup",
          "inulin",
          "brown butter syrup",
          "flavored stevia",
          "sweet'n low",
          "fructose",
          "honey powder",
          "berry syrup",
          "date sugar",
          "grape syrup",
          "mastic gum",
          "gum syrup",
          "irish cream syrup",
          "prickly pear syrup",
          "cookie butter syrup",
          "creamed honey",
          "chocolate sugar",
          "lavender sugar"
      ]
  },
  {
      "group_name": "Seasonings & Spice Blends",
      "icon": "seasonings.png",
      "ingredients": [
          "italian seasoning",
          "seasoned salt",
          "curry",
          "garam masala",
          "pumpkin pie spice",
          "taco seasoning",
          "cajun seasoning",
          "dry ranch seasoning",
          "white miso",
          "himalayan salt",
          "lemon & pepper seasoning",
          "liquid smoke",
          "poultry seasoning",
          "red curry",
          "chinese five spice",
          "old bay seasoning",
          "herbes de provence",
          "all-purpose seasoning",
          "chaat masala",
          "creole seasoning",
          "steak seasoning",
          "juniper berry",
          "fleur de sel",
          "thai red curry paste",
          "mixed herbs",
          "green curry",
          "barbecue seasoning",
          "apple pie spice",
          "za'atar",
          "ras el hanout",
          "seafood seasoning",
          "chili con carne seasoning",
          "bagel seasoning",
          "fajita seasoning",
          "gravy mix",
          "tandoori spice",
          "pickling spice",
          "garlic-pepper seasoning",
          "caribbean jerk seasoning",
          "pickling salt",
          "garlic & herb seasoning",
          "greek seasoning",
          "msg",
          "adobo seasoning",
          "sambar powder",
          "smoking wood",
          "smoked salt",
          "dash seasoning",
          "red miso",
          "hot curry",
          "chili-lime seasoning",
          "salt-free seasoning",
          "bouquet garni",
          "yellow miso",
          "carne asada seasoning",
          "curing salt",
          "pav bhaji masala",
          "dukkah",
          "mexican seasoning",
          "seasoned pepper",
          "crab boil seasoning",
          "chipotle seasoning",
          "shichimi togarashi",
          "truffle salt",
          "rib rub",
          "furikake",
          "biryani masala",
          "togarashi",
          "chana masala",
          "meat masala",
          "harissa spice blend",
          "cheese powder",
          "grey sea salt",
          "brown miso",
          "gingerbread spice",
          "au jus mix",
          "blackening seasoning",
          "mushroom seasoning",
          "lemon & herb seasoning",
          "popcorn seasoning",
          "berbere",
          "pizza seasoning",
          "chai masala",
          "panang curry",
          "kitchen king masala",
          "shawarma seasoning",
          "fines herbes",
          "vanilla salt",
          "mulling spices",
          "thai seasoning",
          "coffee rub",
          "sriracha seasoning",
          "hawaiian salt",
          "tom yum paste",
          "guacamole seasoning",
          "mesquite seasoning",
          "salad seasoning",
          "beef stew seasoning",
          "baharat",
          "fish masala"
      ]
  },
  {
      "group_name": "Baking",
      "icon": "baking_flours.png",
      "ingredients": [
          "flour",
          "vanilla",
          "baking powder",
          "baking soda",
          "cornstarch",
          "yeast",
          "dark chocolate chips",
          "chocolate chips",
          "whole-wheat flour",
          "shredded coconut",
          "almond flour",
          "self-raising flour",
          "cornmeal",
          "baking mix",
          "pastry flour",
          "coconut flake",
          "coconut flour",
          "cream of tartar",
          "cake flour",
          "bread flour",
          "almond meal",
          "unbleached all-purpose flour",
          "white baking chips",
          "flaxseed meal",
          "gluten-free flour",
          "rice flour",
          "yellow cake mix",
          "tapioca starch",
          "chickpea flour",
          "xanthan gum",
          "oat flour",
          "whole-wheat pastry flour",
          "candy sprinkles",
          "chocolate cake mix",
          "spelt",
          "brownie mix",
          "arrowroot flour",
          "potato starch",
          "butterscotch chips",
          "peanut butter chips",
          "crystallized ginger",
          "buckwheat flour",
          "brown rice flour",
          "pectin",
          "rye flour",
          "psyllium husk",
          "semolina flour",
          "glutinous rice flour",
          "refined flour",
          "sweetened coconut flake",
          "pancake mix",
          "marzipan",
          "toffee bits",
          "corn muffin mix",
          "coffee bean",
          "cornbread mix",
          "spice cake mix",
          "masa harina",
          "sorghum flour",
          "cinnamon chips",
          "red velvet cake mix",
          "baking chips",
          "sago",
          "sugar cookie mix",
          "matzo meal",
          "whipped cream stabilizer",
          "vital wheat gluten",
          "coconut chips",
          "cassava flour",
          "hazelnut flour",
          "quinoa flour",
          "finger millet flour",
          "meringue powder",
          "angel food cake mix",
          "mint baking chips",
          "fondant",
          "white cornmeal",
          "gluten-free baking flour",
          "mincemeat",
          "millet flour",
          "einkorn flour",
          "self-rising cornmeal",
          "gluten-free cake mix",
          "gluten-free self-raising flour",
          "peanut flour",
          "coconut powder",
          "carob powder",
          "ready-made icing",
          "teff flour",
          "potato flour",
          "sweet bean paste",
          "fruit salt",
          "guar gum",
          "tapioca pearls",
          "instant flour",
          "seasoned flour",
          "soy flour",
          "oat fiber",
          "amaranth flour",
          "gluten-free panko"
      ]
  },
  {
      "group_name": "Pre-Made Doughs & Wrappers",
      "icon": "baking_and_grains.png",
      "ingredients": [
          "pie crust",
          "puff pastry",
          "pizza crust",
          "refrigerated crescent rolls",
          "phyllo",
          "biscuit dough",
          "dumpling wrapper",
          "rice paper",
          "sourdough starter",
          "cookie dough",
          "graham cracker crust",
          "egg roll wrapper",
          "bread dough",
          "butter puff pastry",
          "frozen dinner roll",
          "mini phyllo",
          "cinnamon roll dough",
          "gyoza wrapper",
          "dosa batter",
          "puff pastry shells",
          "wontons",
          "wonton strips",
          "fresh pasta dough",
          "gluten-free pizza crust",
          "idli batter",
          "chocolate pie crust",
          "croissant dough",
          "kataifi",
          "brisee",
          "sausage rolls",
          "tofu skins",
          "chocolate crumb crust",
          "frozen pizza rolls",
          "korean rice cake",
          "corn dogs",
          "empanada wrapper",
          "rough-puff pastry",
          "sourdough discard",
          "tortilla dough",
          "gingerbread cookie dough",
          "yufka",
          "cob loaf",
          "egg wrap",
          "samosa sheet",
          "brick pastry"
      ]
  },
  {
      "group_name": "Grains & Cereals",
      "icon": "porridge.png",
      "ingredients": [
          "rolled oats",
          "white rice",
          "long-grain white rice",
          "quinoa",
          "brown rice",
          "quick-cooking oats",
          "cooked rice",
          "breakfast cereal",
          "risotto rice",
          "rice cereal",
          "couscous",
          "wild rice",
          "semolina",
          "jasmine rice",
          "polenta",
          "granola cereal",
          "bulgur",
          "cauliflower rice",
          "pearl barley",
          "farro",
          "grits",
          "barley",
          "steel cut oats",
          "wheat germ",
          "oat bran",
          "instant rice",
          "sushi rice",
          "millet",
          "glutinous rice",
          "hominy",
          "red quinoa",
          "wheat bran",
          "raw buckwheat",
          "instant oats",
          "wheat berries",
          "poha",
          "yellow rice",
          "black rice",
          "muesli",
          "fine semolina",
          "kasha",
          "quinoa flakes",
          "amaranth",
          "puffed rice",
          "cracked wheat",
          "pearled farro",
          "paella rice",
          "freekeh",
          "sorghum",
          "red rice",
          "idli rice",
          "mexican rice",
          "brown jasmine rice",
          "cream of wheat",
          "rice pilaf",
          "weetabix",
          "barnyard millet",
          "gluten-free cereals",
          "jambalaya rice mix",
          "blue cornmeal",
          "whole-grain oats",
          "cilantro lime rice",
          "puffed quinoa",
          "black glutinous rice",
          "dirty rice mix",
          "hulled barley",
          "finger millet",
          "puffed wheat",
          "broccoli rice",
          "foxtail millet",
          "brown long grain rice",
          "fried rice",
          "pearl millet",
          "matta rice",
          "rye berries",
          "kodo millet",
          "spelt flakes",
          "oat groats",
          "teff",
          "sprouted brown rice",
          "chicken-flavor rice",
          "little millet",
          "rye flakes",
          "puffed amaranth",
          "biriyani rice",
          "coconut rice",
          "red beans & rice mix",
          "rice bran",
          "spelt berry",
          "texmati rice",
          "amaranth flakes",
          "puffed kamut",
          "bamboo rice",
          "pearled sorghum",
          "red rice poha",
          "shirataki rice",
          "sona masoori rice",
          "grünkern",
          "jeera rice",
          "saffron rice"
      ]
  },
  {
      "group_name": "Legumes",
      "icon": "Legumes.png",
      "ingredients": [
          "peas",
          "green beans",
          "black beans",
          "chickpea",
          "kidney beans",
          "white beans",
          "lentils",
          "snow peas",
          "snap peas",
          "red lentils",
          "cannellini beans",
          "bean sprouts",
          "edamame",
          "green lentils",
          "pinto beans",
          "urad dal",
          "lima beans",
          "chana dal",
          "fava beans",
          "black-eyed peas",
          "moong dal",
          "split peas",
          "pigeon peas",
          "red beans",
          "mung bean sprout",
          "pea shoots",
          "soybeans",
          "mung beans",
          "string beans",
          "yellow split peas",
          "black lentils",
          "borlotti beans",
          "aquafaba",
          "chana",
          "snake beans",
          "yellow lentils",
          "fermented black beans",
          "kala chana",
          "mixed beans",
          "black gram",
          "wax beans",
          "dried peas",
          "white pea",
          "pink beans",
          "lentil sprouts",
          "field peas",
          "black soybeans",
          "gigantes",
          "flageolets",
          "horse gram",
          "green chickpea",
          "soy sprouts",
          "brown beans",
          "cluster beans",
          "mayocoba beans",
          "winged beans",
          "castelluccio lentils",
          "golden wax beans",
          "moth beans",
          "hara chana",
          "hyacinth beans",
          "lupini beans",
          "natto",
          "chickpea sprouts",
          "petai",
          "scarlet runner beans",
          "sugar beans",
          "honey beans",
          "soy flakes"
      ]
  },
  {
      "group_name": "Pasta",
      "icon": "past.png",
      "ingredients": [
          "short-cut pasta",
          "spaghetti",
          "macaroni",
          "egg noodle",
          "spiral pasta",
          "lasagna",
          "linguine",
          "fettuccine",
          "orzo",
          "pasta shell",
          "bow-tie pasta",
          "tortellini",
          "noodle",
          "rice noodles",
          "rigatoni",
          "gnocchi",
          "angel hair pasta",
          "ramen noodles",
          "vermicelli",
          "tagliatelle",
          "ziti",
          "ravioli",
          "soba noodles",
          "orecchiette",
          "israeli couscous",
          "zoodles",
          "udon noodles",
          "ditalini",
          "rice vermicelli",
          "gluten-free pasta",
          "pappardelle",
          "glass noodles",
          "mac 'n cheese",
          "penne rigate",
          "manicotti",
          "bucatini",
          "cannelloni",
          "thai rice noodles",
          "rotelle",
          "chicken ramen",
          "shirataki noodles",
          "brown rice pasta",
          "pierogi",
          "soup pasta",
          "cavatelli",
          "sweet potato noodles",
          "acini di pepe",
          "instant noodle",
          "radiatore",
          "somen noodles",
          "gluten-free noodles",
          "yakisoba noodles",
          "beef ravioli",
          "spaetzle",
          "hakka noodles",
          "kluski noodles",
          "fideo pasta",
          "kelp noodles",
          "rice-a-roni",
          "paccheri",
          "pasta salad mix",
          "beef ramen",
          "yolk-free noodles",
          "black bean pasta",
          "matzo farfel",
          "spinach fettuccine",
          "banh pho",
          "potato dumplings",
          "frozen dumplings",
          "fregola",
          "beef tortellini",
          "cauliflower gnocchi",
          "misua",
          "butternut squash noodles",
          "palmini",
          "trahanas",
          "busiate",
          "lobster ravioli",
          "mafalde",
          "trottole",
          "casarecce",
          "mandu",
          "pork ramen",
          "pot pie noodle",
          "mie noodle",
          "semiya",
          "bean pasta",
          "bean sheets",
          "hilopites",
          "jjolmyeon",
          "naengmyeon noodles",
          "quinoa pasta",
          "squash ravioli",
          "yuba noodles",
          "high-protein pasta"
      ]
  },
  {
      "group_name": "Bread & Salty Snacks",
      "icon": "sandwiches.png",
      "ingredients": [
          "bread",
          "bread crumbs",
          "panko",
          "flour tortillas",
          "corn tortillas",
          "crackers",
          "baguette",
          "tortilla chips",
          "pretzels",
          "pita",
          "sourdough bread",
          "seasoned bread crumbs",
          "rustic italian bread",
          "popcorn",
          "croutons",
          "whole-wheat tortillas",
          "english muffin",
          "brioche",
          "rye bread",
          "flatbread",
          "dry-roasted peanuts",
          "stuffing mix",
          "potato chips",
          "taco shells",
          "naan",
          "cornbread",
          "tater tots",
          "unpopped popcorn",
          "corn chips",
          "bagel",
          "croissants",
          "pork rinds",
          "pumpernickel",
          "sweet bread",
          "gluten free bread",
          "pita chips",
          "hawaiian rolls",
          "potato bread",
          "breadsticks",
          "focaccia",
          "muffin",
          "tostada shells",
          "gluten-free bread crumbs",
          "crispy fried onions",
          "matzo",
          "yeast extract spread",
          "garlic bread",
          "challah",
          "roasted gram",
          "cheese crackers",
          "panettone",
          "crostini",
          "rice cake",
          "gluten-free tortillas",
          "sev",
          "sweet potato fries",
          "corn muffin",
          "papad",
          "vegetable chips",
          "spinach wraps",
          "plantain chips",
          "roasted chickpeas",
          "pretzel bun",
          "boboli",
          "cheetos",
          "crumpet",
          "chapati",
          "seed bread",
          "keto bread",
          "bread bowl",
          "cornbread stuffing mix",
          "low-carb wraps",
          "milk bread",
          "frozen onion rings",
          "sprouted grain bread",
          "rice crackers",
          "rusks",
          "corn nuts",
          "pav bun",
          "banana bread",
          "polarbröd",
          "sprouted bread",
          "fruit bread",
          "crispbread",
          "roti bread",
          "prawn crackers",
          "popcorn shrimp",
          "chocolate muffin",
          "ezekiel bread",
          "melba toast",
          "wasabi peas",
          "bao bun",
          "yorkshire pudding",
          "arabic bread",
          "barley rusks",
          "seaweed snack",
          "zwieback",
          "oven chips",
          "taco kit",
          "gluten free pita"
      ]
  },
  {
      "group_name": "Oils & Fats",
      "icon": "oils.png",
      "ingredients": [
          "olive oil",
          "vegetable oil",
          "extra virgin olive oil",
          "canola oil",
          "coconut oil",
          "cooking spray",
          "sesame oil",
          "frying oil",
          "sunflower oil",
          "avocado oil",
          "toasted sesame oil",
          "peanut oil",
          "grapeseed oil",
          "lard",
          "pork fat",
          "corn oil",
          "virgin coconut oil",
          "mustard oil",
          "chili oil",
          "garlic oil",
          "walnut oil",
          "truffle oil",
          "safflower oil",
          "cacao butter",
          "salad oil",
          "duck fat",
          "rice bran oil",
          "soybean oil",
          "white truffle oil",
          "medium-chain triglyceride",
          "butter-flavored cooking spray",
          "flaxseed oil",
          "pumpkin seed oil",
          "hazelnut oil",
          "coconut oil spray",
          "almond oil",
          "lemon oil",
          "macadamia oil",
          "goose fat",
          "palm oil",
          "basil oil",
          "schmaltz",
          "tallow",
          "pistachio oil",
          "herb-infused olive oil",
          "hot sesame oil",
          "pecan oil",
          "beef fat",
          "roasted peanut oil",
          "argan oil",
          "crisco oil",
          "shea butter",
          "black sesame oil",
          "red palm oil",
          "lamb fat",
          "sichuan peppercorn oil",
          "castor oil",
          "shallot oil",
          "achiote oil",
          "jojoba oil",
          "wheat germ oil",
          "blood orange olive oil",
          "oregano oil",
          "hemp seed oil",
          "cottonseed oil",
          "ginger oil",
          "rosehip seed oil",
          "marula oil",
          "moringa seed oil",
          "white cacao butter",
          "black seed oil"
      ]
  },
  {
      "group_name": "Dressings & Vinegars",
      "icon": "salads.png",
      "ingredients": [
          "mayonnaise",
          "apple cider vinegar",
          "balsamic vinegar",
          "vinegar",
          "red wine vinegar",
          "rice wine vinegar",
          "white wine vinegar",
          "ranch dressing",
          "italian dressing",
          "sherry vinegar",
          "distilled white vinegar",
          "white balsamic vinegar",
          "sweet chilli sauce",
          "champagne vinegar",
          "vinaigrette dressing",
          "balsamic vinaigrette",
          "seasoned rice vinegar",
          "blue cheese dressing",
          "caesar dressing",
          "thousand island",
          "malt vinegar",
          "black vinegar",
          "canola mayonnaise",
          "raspberry vinegar",
          "japanese mayonnaise",
          "tarragon vinegar",
          "greek vinaigrette",
          "sesame dressing",
          "honey mustard dressing",
          "aioli sauce",
          "french dressing",
          "spicy mayo",
          "poppyseed dressing",
          "catalina dressing",
          "verjuice",
          "raspberry vinaigrette",
          "cane vinegar",
          "red wine vinaigrette",
          "russian dressing",
          "coleslaw dressing",
          "avocado oil mayonnaise",
          "buttermilk ranch dressing",
          "mustard-mayonnaise blend",
          "sushi vinegar",
          "champagne vinaigrette",
          "sun-dried tomato vinaigrette",
          "creamy balsamic dressing",
          "coconut vinegar",
          "garlic mayonnaise",
          "ume plum vinegar",
          "brown rice vinegar",
          "spicy ranch dressing",
          "cilantro dressing",
          "creamy dressing",
          "fig balsamic",
          "green goddess dressing",
          "chipotle aioli",
          "spiced vinegar",
          "lime vinaigrette",
          "onion salad dressing",
          "miso dressing",
          "white balsamic vinaigrette",
          "chardonnay vinegar",
          "prepared coleslaw dressing",
          "honey vinegar",
          "lemon vinegar",
          "tandoori mayonnaise",
          "chili vinegar",
          "chili-lime dressing",
          "moscatel vinegar",
          "pomegranate vinegar",
          "vinegar powder",
          "mango vinaigrette",
          "sweet onion dressing",
          "avocado-lime dressing",
          "mustard aioli",
          "caramelised onion dressing"
      ]
  },
  {
      "group_name": "Condiments",
      "icon": "condiments.png",
      "ingredients": [
          "soy sauce",
          "dijon mustard",
          "worcestershire",
          "hot sauce",
          "ketchup",
          "mustard",
          "fish sauce",
          "bbq sauce",
          "sriracha",
          "wholegrain mustard",
          "tamari",
          "oyster sauce",
          "chili sauce",
          "ginger-garlic paste",
          "brown mustard",
          "teriyaki sauce",
          "wing sauce",
          "prepared horseradish",
          "ginger paste",
          "dark soy sauce",
          "coconut aminos",
          "chili paste",
          "harissa",
          "chili-garlic sauce",
          "tamarind paste",
          "pomegranate molasses",
          "gochujang",
          "wasabi",
          "mango chutney",
          "honey mustard",
          "sambal oelek",
          "english mustard",
          "preserved lemon",
          "kecap manis",
          "chutney",
          "shrimp paste",
          "picante sauce",
          "thai sweet chili sauce",
          "sweet and sour sauce",
          "chili-garlic paste",
          "green chutney",
          "tartar sauce",
          "liquid aminos",
          "hot pepper jelly",
          "ponzu",
          "mexican hot sauce",
          "sambal",
          "bonito flakes",
          "green chilli sauce",
          "red pepper jelly",
          "crispy onions",
          "thai chili paste",
          "peri peri",
          "green chilli paste",
          "mint jelly",
          "pepper paste",
          "horseradish mustard",
          "aji amarillo",
          "mustard paste",
          "tamarind chutney",
          "onion marmalade",
          "ginger chili paste",
          "yuzu juice",
          "giardiniera",
          "hp sauce",
          "chermoula",
          "duck sauce",
          "tonkatsu sauce",
          "doubanjiang",
          "chili crisp",
          "black soy sauce",
          "doenjang",
          "korean bbq sauce",
          "maggi sauce",
          "chinese mustard",
          "lime pickle",
          "karashi",
          "chamoy",
          "mushroom soy sauce",
          "taucheo",
          "german mustard",
          "yuzu kosho",
          "banana ketchup",
          "remoulade",
          "hot bean paste",
          "patis",
          "pickapeppa sauce",
          "eel sauce",
          "guk ganjang",
          "salsa lizano",
          "white bbq sauce",
          "grape must",
          "shrimp sauce",
          "shrimp powder",
          "chili puree",
          "fermented tofu",
          "green harissa",
          "sweet soybean paste",
          "szechuan sauce",
          "henderson's relish"
      ]
  },
  {
      "group_name": "Canned Food",
      "icon": "canned_veggies.png",
      "ingredients": [
          "canned tomato",
          "capers",
          "green olives",
          "canned chickpea",
          "black olives",
          "canned black beans",
          "canned pumpkin",
          "kalamata olives",
          "canned tuna",
          "pickle",
          "canned pineapple",
          "chipotle in adobo",
          "roasted red peppers",
          "canned anchovy",
          "maraschino cherry",
          "tomatoes with green chiles",
          "canned artichoke",
          "canned corn",
          "canned whole tomato",
          "canned kidney beans",
          "canned pie filling",
          "refried beans",
          "canned cannellini beans",
          "sweet pickle relish",
          "sauerkraut",
          "creamed corn",
          "corned beef",
          "canned beans",
          "pickled jalapenos",
          "diced green chiles",
          "canned pinto beans",
          "sun-dried tomatoes in oil",
          "canned mandarin oranges",
          "kimchi",
          "chili beans",
          "canned crab",
          "canned peaches",
          "bamboo shoot",
          "baked beans",
          "canned mushroom",
          "canned salmon",
          "pickling juice",
          "dill pickle relish",
          "canned clam",
          "canned water chestnut",
          "canned black-eyed peas",
          "pickled ginger",
          "canned whole green chiles",
          "canned apple",
          "canned green beans",
          "spam",
          "hearts of palm",
          "chili with beans",
          "pickled onions",
          "canned lentils",
          "fruit cocktail",
          "canned peas",
          "pickled red onion",
          "pimiento-stuffed green olives",
          "canned pork",
          "pickled beets",
          "canned cherry tomato",
          "bread & butter pickles",
          "canned apricot",
          "canned sweet potato",
          "canned sour cherry",
          "peppadew pepper",
          "canned pear",
          "pork and beans",
          "onion paste",
          "canned baby corn",
          "pickled vegetables",
          "chili without beans",
          "mexican-style corn",
          "pickled pepper",
          "pumpkin pie filling",
          "fire-roasted green chiles",
          "banana pepper rings",
          "ranch-style beans",
          "canned chicken breast",
          "canned carrot",
          "canned cherry",
          "canned mixed beans",
          "canned sardines",
          "canned lychee",
          "ginger in syrup",
          "taggiasca olives",
          "canned jackfruit",
          "tomato relish",
          "canned potato",
          "canned mango",
          "cranberry relish",
          "pickled herring",
          "canned asparagus",
          "red pepper relish",
          "canned fava beans",
          "canned peas and carrots",
          "corn relish",
          "florina peppers",
          "pickled cherry peppers"
      ]
  },
  {
      "group_name": "Sauces, Spreads & Dips",
      "icon": "sauces.png",
      "ingredients": [
          "tomato paste",
          "peanut butter",
          "tomato sauce",
          "salsa",
          "tahini",
          "pesto",
          "pasta sauce",
          "marinara sauce",
          "hoisin sauce",
          "pico de gallo",
          "enchilada sauce",
          "stewed tomatoes",
          "guacamole",
          "hummus",
          "salsa verde",
          "fire-roasted tomato",
          "alfredo sauce",
          "balsamic glaze",
          "anchovy paste",
          "steak sauce",
          "chunky peanut butter",
          "tzatziki",
          "beef gravy",
          "taco sauce",
          "sun-dried tomato pesto",
          "green enchilada sauce",
          "béchamel sauce",
          "cheese dip",
          "horseradish sauce",
          "plum sauce",
          "garlic butter",
          "hollandaise sauce",
          "cocktail sauce",
          "tapenade",
          "black bean sauce",
          "pimento cheese spread",
          "stir-fry sauce",
          "turkey gravy",
          "chicken gravy",
          "thai peanut sauce",
          "demi-glace",
          "sloppy joe sauce",
          "sofrito",
          "mustard sauce",
          "sun-dried tomato paste",
          "french onion dip",
          "chimichurri sauce",
          "herb butter",
          "bolognese sauce",
          "curry sauce",
          "liver spread",
          "browning sauce",
          "schezwan sauce",
          "pork gravy",
          "orange sauce",
          "country gravy",
          "pineapple salsa",
          "mushroom gravy",
          "chicken demi-glace",
          "mango salsa",
          "olive paste",
          "spinach dip",
          "japanese curry",
          "artichoke dip",
          "black truffle butter",
          "black sesame paste",
          "roasted red pepper hummus",
          "whipped cream cheese spread",
          "bacon jam",
          "tikka masala sauce",
          "vodka sauce",
          "garlic hummus",
          "green taco sauce",
          "kung pao sauce",
          "sausage gravy",
          "cheese spread",
          "corn salsa",
          "mole paste",
          "onion gravy",
          "pad thai sauce",
          "cheddar sauce",
          "butter chicken sauce",
          "deviled ham spread",
          "garlic pasta sauce",
          "garlic spread",
          "green olive tapenade",
          "black pepper sauce",
          "char siu sauce",
          "sesame sauce",
          "schezwan chutney",
          "thai red curry sauce",
          "kale pesto",
          "tarama",
          "white pizza sauce",
          "white truffle butter",
          "mango sauce",
          "salsa con queso dip",
          "ssamjang",
          "yum yum sauce",
          "arugula pesto"
      ]
  },
  {
      "group_name": "Soups, Stews & Stocks",
      "icon": "soups_and_stews.png",
      "ingredients": [
          "chicken broth",
          "vegetable broth",
          "chicken stock",
          "beef broth",
          "beef stock",
          "cream of mushroom",
          "bouillon cube",
          "cream of chicken",
          "onion soup mix",
          "tomato soup",
          "fish stock",
          "soup base",
          "cream of celery",
          "clam juice",
          "cheese soup",
          "bone broth",
          "dashi",
          "onion soup",
          "veal stock",
          "chicken bone broth",
          "turkey stock",
          "lamb stock",
          "turkey broth",
          "beef consommé",
          "stock paste",
          "cream of potato",
          "golden mushroom soup",
          "seafood stock",
          "chicken soup",
          "turkey drippings",
          "mushroom broth",
          "chicken noodle soup",
          "vegetable soup mix",
          "vegetable soup",
          "ramen noodle soup",
          "nacho cheese soup",
          "shrimp stock",
          "beef dripping",
          "lobster stock",
          "pork stock",
          "cream of broccoli",
          "chicken rice soup",
          "beefy onion soup mix",
          "chicken stock paste",
          "butternut squash soup",
          "clam broth",
          "miso soup",
          "broccoli-cheese soup",
          "duck stock",
          "sinigang mix",
          "vegan chicken broth",
          "ham stock",
          "cream of asparagus",
          "new england clam chowder",
          "beefy mushroom soup",
          "pork broth",
          "cream of shrimp soup",
          "bean soup mix",
          "black bean soup",
          "chicken consommé",
          "cream of bacon",
          "lentil soup",
          "vegetable beef soup",
          "veal broth",
          "chicken soup mix",
          "roasted garlic chicken broth",
          "lobster bisque",
          "bean with bacon soup",
          "clam chowder",
          "condensed chicken gumbo soup",
          "thai ginger broth",
          "tortilla soup base",
          "anchovy stock",
          "chicken drippings",
          "chicken corn chowder",
          "cream of chicken soup mix",
          "shrimp bouillon cube",
          "thai chicken broth",
          "turkey bone broth",
          "lamb broth",
          "minestrone",
          "pork & beans",
          "tomato bisque",
          "venison stock",
          "beef stock paste",
          "bovril",
          "ham-flavored concentrate",
          "noodle soup mix",
          "potato soup mix",
          "callaloo",
          "oxtail soup",
          "split pea soup",
          "chicken and mushroom soup",
          "chili beef soup",
          "corn chowder",
          "cream of cauliflower",
          "dashida",
          "green pea soup",
          "pho broth"
      ]
  },
  {
      "group_name": "Desserts & Sweet Snacks",
      "icon": "desserts_and_snacks.png",
      "ingredients": [
          "cocoa",
          "dark chocolate",
          "dark cocoa",
          "chocolate",
          "marshmallow",
          "applesauce",
          "gelatin",
          "white chocolate",
          "graham cracker",
          "graham cracker crumbs",
          "oreo",
          "instant pudding",
          "chocolate hazelnut spread",
          "chocolate candy",
          "dutch-process cocoa",
          "raspberry jam",
          "biscuits",
          "caramel sauce",
          "apricot jam",
          "candy coating",
          "raw cacao powder",
          "strawberry jam",
          "marshmallow creme",
          "candy",
          "baking chocolate",
          "jam",
          "orange marmalade",
          "wafer",
          "cookies",
          "jello",
          "cranberry sauce",
          "chocolate pudding",
          "peanut butter cups",
          "candy cane",
          "ginger snaps",
          "cacao nibs",
          "lady fingers",
          "fudge sauce",
          "chocolate chip cookies",
          "caramel candies",
          "chocolate cookies",
          "apple butter",
          "peppermint candy",
          "cinnamon roll",
          "candied cherry",
          "currant jelly",
          "butter cookies",
          "candied ginger",
          "angel food cake",
          "couverture chocolate",
          "peach preserves",
          "candied peel",
          "cherry jam",
          "dark couverture chocolate",
          "white baking chocolate",
          "chocolate wafer",
          "grape jelly",
          "instant lemon pudding",
          "waffles",
          "agar agar",
          "cookie butter",
          "fig jam",
          "candied fruit",
          "apple jelly",
          "gummies",
          "almond cookies",
          "candy corn",
          "blueberry jam",
          "blackberry preserves",
          "butterscotch",
          "ice-cream cone",
          "egg candies",
          "marmalade",
          "sugar cookies",
          "strawberry puree",
          "chocolate powder",
          "licorice",
          "chocolate-covered espresso bean",
          "pineapple jam",
          "banana pudding",
          "sponge cake",
          "sorbet",
          "mexican chocolate",
          "plum jam",
          "white couverture",
          "cinnamon candy",
          "white chocolate pudding",
          "peanut-butter sandwich cookies",
          "pumpkin butter",
          "chocolate peanut butter",
          "guava paste",
          "butterscotch pudding mix",
          "fudge",
          "chocolate spread",
          "strawberry sauce",
          "hershey kisses",
          "doughnut",
          "biscotti",
          "peppermint patties",
          "candied pineapple"
      ]
  },
  {
      "group_name": "Wine, Beer & Spirits",
      "icon": "alcohol.png",
      "ingredients": [
          "white wine",
          "red wine",
          "whisky",
          "rum",
          "vodka",
          "beer",
          "orange liqueur",
          "cider",
          "tequila",
          "sherry",
          "gin",
          "brandy",
          "bitters",
          "mirin",
          "white rum",
          "coffee liqueur",
          "champagne",
          "vermouth",
          "irish cream",
          "amaretto",
          "marsala wine",
          "cognac",
          "sparkling wine",
          "sake",
          "shaoxing wine",
          "rice wine",
          "dry vermouth",
          "coconut rum",
          "liqueur",
          "curacao",
          "dessert wine",
          "port wine",
          "kirsch",
          "peach schnapps",
          "white cooking wine",
          "apple brandy",
          "rosé wine",
          "anise liqueur",
          "herbal liqueur",
          "limoncello",
          "elderflower liqueur",
          "hazelnut liqueur",
          "raspberry liqueur",
          "melon liqueur",
          "peach liqueur",
          "banana liqueur",
          "creme de cacao",
          "schnapps",
          "absinthe",
          "madeira wine",
          "aperol",
          "vanilla vodka",
          "cinnamon alcohol",
          "creme de menthe",
          "apricot brandy",
          "cachaça",
          "chocolate liqueur",
          "elderflower cordial",
          "bénédictine",
          "ginger liqueur",
          "sloe gin",
          "creme de cassis",
          "maraschino",
          "red cooking wine",
          "cream sherry",
          "bloody mary mix",
          "gold rum",
          "sparkling rosé",
          "lime cordial",
          "drambuie",
          "grappa",
          "strawberry liqueur",
          "galliano",
          "mezcal",
          "ginger wine",
          "peppermint liqueur",
          "white port",
          "advocaat",
          "piña colada mix",
          "pumpkin ale",
          "daiquiri mix",
          "blackberry schnapps",
          "coconut liqueur",
          "rumchata liqueur",
          "blackberry brandy",
          "gentian liqueur",
          "chocolate bitters",
          "vanilla liqueur",
          "moonshine",
          "pisco",
          "plum wine",
          "grapefruit bitters",
          "peach brandy",
          "sangria",
          "white chocolate liqueur",
          "apple liqueur",
          "pear brandy",
          "sauternes",
          "rhum agricole",
          "amarula cream"
      ]
  },
  {
      "group_name": "Beverages",
      "icon": "beverages.png",
      "ingredients": [
          "orange juice",
          "coffee",
          "club soda",
          "espresso",
          "pineapple juice",
          "apple juice",
          "tea",
          "cranberry juice",
          "tomato juice",
          "coconut water",
          "pomegranate juice",
          "matcha powder",
          "grapefruit juice",
          "coke",
          "lemonade",
          "ginger ale",
          "eggnog",
          "ginger beer",
          "orange juice concentrate",
          "lemon lime soda",
          "sprite",
          "cream of coconut",
          "green tea",
          "lemonade concentrate",
          "root beer",
          "chai tea",
          "drinking chocolate",
          "tonic water",
          "malted milk powder",
          "cherry juice",
          "sour mix",
          "mango juice",
          "hibiscus",
          "tea leaves",
          "grape juice",
          "limeade concentrate",
          "carrot juice",
          "dr pepper",
          "iced tea",
          "white grape juice",
          "fruit juice",
          "watermelon juice",
          "tangerine juice",
          "kombucha",
          "passion-fruit juice",
          "apricot juice",
          "orange soda",
          "beet juice",
          "margarita mix",
          "peach juice",
          "energy drink",
          "kool aid",
          "chamomile tea",
          "pear juice",
          "cream soda",
          "mountain dew",
          "tamarind water",
          "rooibos tea",
          "tamarind juice",
          "grapefruit soda",
          "lime soda",
          "raspberry juice",
          "clamato",
          "guava juice",
          "jasmine tea",
          "iced coffee concentrate",
          "strawberry juice",
          "green tea leaves",
          "rose syrup",
          "v8 juice",
          "blueberry juice",
          "sweetened lime juice",
          "beetroot juice",
          "lemonade mix",
          "thai tea",
          "pineapple juice concentrate",
          "aloe vera juice",
          "juice blend",
          "prune juice",
          "butterfly pea flower",
          "lapsang souchong",
          "sparkling cider",
          "berry juice",
          "passion tea",
          "white tea",
          "strawberry soda",
          "blackcurrant juice",
          "peppermint tea",
          "lychee juice",
          "herbal tea",
          "banana juice",
          "chicory coffee",
          "cranberry-raspberry juice",
          "raspberry lemonade",
          "decaf coffee",
          "pumpkin spice coffee",
          "cherry soda",
          "lemon water",
          "bitter lemon soda",
          "pepsi"
      ]
  },
  {
      "group_name": "Supplements & Extracts",
      "icon": "supplements.png",
      "ingredients": [
          "almond extract",
          "food coloring",
          "nutritional yeast",
          "peppermint extract",
          "protein powder",
          "lemon extract",
          "coconut extract",
          "rose water",
          "orange extract",
          "rum extract",
          "rock salt",
          "maple extract",
          "chocolate protein powder",
          "collagen",
          "liquid egg white",
          "orange blossom water",
          "peanut butter powder",
          "vegan protein powder",
          "citric acid",
          "maca powder",
          "essence",
          "strawberry extract",
          "spirulina",
          "brewer's yeast",
          "coffee extract",
          "butter extract",
          "anise extract",
          "chocolate extract",
          "raspberry extract",
          "lavender oil",
          "cannabis",
          "banana extract",
          "bee pollen",
          "essential oil",
          "peanut powder",
          "caramel extract",
          "root beer extract",
          "vitamin c",
          "cannabutter",
          "acai powder",
          "egg white powder",
          "hemp protein",
          "ube flavoring",
          "hazelnut extract",
          "glucomannan",
          "tamarind extract",
          "butterscotch flavor",
          "cherry extract",
          "freeze-dried strawberry powder",
          "kewra water",
          "pineapple extract",
          "cinnamon extract",
          "lemon juice concentrate",
          "cannabis milk",
          "carnation breakfast essentials",
          "lime essential oil",
          "malt extract",
          "kombucha starter",
          "casein",
          "chocolate collagen",
          "soy lecithin",
          "lime juice concentrate",
          "camu powder",
          "pandan extract",
          "wheatgrass powder",
          "ashwagandha",
          "cbd oil",
          "chlorella",
          "rice protein powder",
          "rosemary essential oil",
          "tea-tree oil",
          "mango extract",
          "probiotics",
          "maltodextrin",
          "fish oil",
          "vitamin e",
          "egg powder",
          "vitamin d",
          "wine yeast",
          "activated charcoal",
          "clove oil",
          "corn extract",
          "grapefruit essential oil",
          "greens powder",
          "barley grass",
          "reishi mushroom",
          "blueberry extract",
          "calcium lactate",
          "daily vitamins",
          "champagne yeast",
          "raspberry powder",
          "sunflower lecithin",
          "thc",
          "banana powder",
          "berry powder",
          "creatine",
          "goji berry powder",
          "magnesium",
          "maqui",
          "moringa powder"
      ]
  }
]